### ISSUE TITLE
(IMO) Bug in impact and pathlengths

### ISSUE THREAD

**Issue by LucaGiudice** [AlexChristensen/NetworkToolbox#3] opened 2019-05-02 17:16 UTC
Hi,
In my opinion there is a bug in the impact function that calls pathlengths.
When I provide a graph, a node is removed and another node becomes isolated and disconnected from the rest of graph, the function returns the error:
>'names' attribute must be the same length as the vector

Tracing back the error derives from:
> line7 of impact
> line31 of pathlengths
The error seems understable because aspli is computed from any node which distance is different from 0 in the line 20. However, the matrix A keeps all the columns except the one that has been removed.

E.g. 
A=10x10
impact(A)
one node is removed
A=9x9
aspli is computed but one new node is isolated and its distances equal to 0
aspli has length 8
names(aspli) = colnames(A) --> error

**Comment by AlexChristensen** [comment] 2019-05-09 20:01
Hi @LucaGiudice,

Thanks for pointing out this issue. I believe that this is occurring with the current version of NetworkToolbox on CRAN (version 1.2.3). I am able to reproduce this error with this version.

With the next release, this bug should be fixed. For now, please try installing NetworkToolbox from GitHub:

`devtools::install_github("AlexChristensen/NetworkToolbox")`

This is the upcoming version 1.2.4 and I believe it fixes this issue (I was not able to reproduce the same error with this version).

Please let me know if this resolves this issue or not.

**Closed as completed** 2019-05-23 17:22 UTC
Labels: bug
